// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bclrdA3nZ4zGEtTxxtVKuIPY2m_OWNE',
    appId: '1:166889945227:android:9e6726b817345ef574bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    storageBucket: 'orangepriceapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQTeKlcqgFjgXnyZmukHq2Sdt5sZW2LQ',
    appId: '1:166889945227:web:cea2fd1a1a2077ef74bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    authDomain: 'orangepriceapp.firebaseapp.com',
    storageBucket: 'orangepriceapp.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQTeKlcqgFjgXnyZmukHq2Sdt5sZW2LQ',
    appId: '1:166889945227:web:cea2fd1a1a2077ef74bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    authDomain: 'orangepriceapp.firebaseapp.com',
    storageBucket: 'orangepriceapp.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03ps9rN6984kcYm1mLke_LKMK-pmflkw',
    appId: '1:166889945227:ios:af841a878e8b16bd74bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    storageBucket: 'orangepriceapp.firebasestorage.app',
    iosBundleId: 'com.example.orangecalculatorapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03ps9rN6984kcYm1mLke_LKMK-pmflkw',
    appId: '1:166889945227:ios:af841a878e8b16bd74bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    storageBucket: 'orangepriceapp.firebasestorage.app',
    iosBundleId: 'com.example.orangecalculatorapp',
  );

}