// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bclrdA3nZ4zGEtTxxtVKuIPY2m_OWNE',
    appId: '1:166889945227:android:9e6726b817345ef574bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    storageBucket: 'orangepriceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03ps9rN6984kcYm1mLke_LKMK-pmflkw',
    appId: '1:166889945227:ios:af841a878e8b16bd74bc8e',
    messagingSenderId: '166889945227',
    projectId: 'orangepriceapp',
    storageBucket: 'orangepriceapp.firebasestorage.app',
    iosBundleId: 'com.example.orangecalculatorapp',
  );

}